version: 2
jobs:
  ui-tests:
    docker:
      - image: circleci/openjdk:11.0.8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Running tests
          command: mvn clean test

      - run:
          name: Generate allure report
          command: mvn io.qameta.allure:allure-maven:report
          when: always
      - store_test_results:
          path: target/surefire-reports/junitreports
          when: always
      - store_artifacts:
          path: target/site/allure-maven-plugin/


workflows:
  version: 2
  commit:
    jobs:
      - ui-tests
  periodical:
    triggers:
      - schedule:
          cron: "5 4 23 2 *"
          filters:
            branches:
              only:
                - master
    jobs:
      - ui-tests
